steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '--build-arg', 'PHP_IMAGE=php:7.0-stretch', '--destination=gcr.io/$PROJECT_ID/build-7.0', '--cache=true', '--cache-ttl=6h', '.' ]
  waitFor: ['-']
  id: 'build-7.0'
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '--build-arg', 'PHP_IMAGE=php:7.1-stretch', '--destination=gcr.io/$PROJECT_ID/build-7.1', '--cache=true', '--cache-ttl=6h', '.' ]
  waitFor: ['-']
  id: 'build-7.1'
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '--build-arg', 'PHP_IMAGE=php:7.2-stretch', '--destination=gcr.io/$PROJECT_ID/build-7.2', '--cache=true', '--cache-ttl=6h', '.' ]
  waitFor: ['-']
  id: 'build-7.2'
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '--build-arg', 'PHP_IMAGE=php:7.3-stretch', '--destination=gcr.io/$PROJECT_ID/build-7.3', '--cache=true', '--cache-ttl=6h', '.' ]
  waitFor: ['-']
  id: 'build-7.3'

- name: 'gcr.io/cloud-builders/docker'
  args: ['run', 'gcr.io/$PROJECT_ID/build-7.0']
  waitFor: ['build-7.0']
  id: 'run-7.0'
- name: 'gcr.io/cloud-builders/docker'
  args: ['run', 'gcr.io/$PROJECT_ID/build-7.1']
  waitFor: ['build-7.1']
  id: 'run-7.1'
- name: 'gcr.io/cloud-builders/docker'
  args: ['run', 'gcr.io/$PROJECT_ID/build-7.2']
  waitFor: ['build-7.2']
  id: 'run-7.2'
- name: 'gcr.io/cloud-builders/docker'
  args: ['run', 'gcr.io/$PROJECT_ID/build-7.3']
  waitFor: ['build-7.3']
  id: 'run-7.3'
images: [
 'gcr.io/$PROJECT_ID/build-7.0',
 'gcr.io/$PROJECT_ID/build-7.1',
 'gcr.io/$PROJECT_ID/build-7.2',
 'gcr.io/$PROJECT_ID/build-7.3'
]
